### ISSUE TITLE
Failed to install QLite library

### ISSUE THREAD

**Issue by ngocdha** [qubiclite/qlite.lib.java#1]
I'm on MacOS High Sierra with Java 10.0.1 and Maven 3.5.4 installed. I followed the instructions, and everything worked fine until I attempted to install the QLite library:

> mvn install

Here's the error I got:

> Reactor Summary:
>
> QLite 0.1 .......................................... SUCCESS [  0.879 s]
> QLite : Library 0.1 ................................ FAILURE [  4.840 s]
>...
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.13:test (default-test) on project qlite: groups/excludedGroups require TestNG or JUnit48+ on project test classpath -> [Help 1]

Here's a screenshot of my terminal
![screen shot 2018-07-08 at 3 31 42 am](https://user-images.githubusercontent.com/34144399/42418612-6060ad50-8261-11e8-9047-e9a72d0cb569.png)

**Comment by vuapo-eth** [comment]
Thank you for reporting. "```groups/excludedGroups require TestNG or JUnit48+ on project test classpath```" seems to be the cause. i hope https://github.com/qubiclite/qlite.lib.java/commit/cd14753247d56b9b0a0bcf74d3bb716b79747b97 fixes that. Please retry with the modified pom.xml and report back.

**Comment by ngocdha** [comment]
It works fine after cd14753. Thanks!

![screen shot 2018-07-08 at 2 07 55 pm](https://user-images.githubusercontent.com/34144399/42423491-64289112-82b8-11e8-89d4-49ffebb3d742.png)

I will close this issue then.
